[build]
functions = "netlify/functions"
# This will be run the site build
command = "npm run build"
# This is the directory is publishing to netlify's CDN
publish = "build"

[dev]
# Local dev command. A.k.a npm start
command = "npm run develop"
functions = "netlify/functions"

[[plugins]]
package = "@netlify/plugin-gatsby"
